#!/bin/bash

${GITHUB_ACCESS_TOKEN:set-the-token-as-env-var}

addrepo(){
    NAME=$1
    URL=$2
    make new repo="$NAME" owner="Todd Greenwood-Geer" company="Enviro Software Solutions, LLC" email="pub+github@zwrob.com" url="$URL"
    pushd ${NAME}
    curl https://api.github.com/orgs/energy-analytics-project/repos?access_token=$GITHUB_ACCESS_TOKEN -d "{\"name\":\"${NAME}\",\"description\":\"CAISO OASIS Energy Report\"}"
    git remote add origin git@github.com:energy-analytics-project/${NAME}.git
    git push origin master
    popd
    git submodule add https://github.com/energy-analytics-project/${NAME}.git data/${NAME}
    rm -rf ./${NAME}
    pushd data/${NAME}
    make proc
    popd
}


# done
#addrepo data-oasis-as-mileage-calc-all http://oasis.caiso.com/oasisapi/SingleZip?queryname=AS_MILEAGE_CALC&anc_type=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#addrepo data-oasis-as-op-rsrv "http://oasis.caiso.com/oasisapi/SingleZip?queryname=AS_OP_RSRV&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1"

# todo
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=AGGR_OUTAGE_SCH&fuel_category=Renewable&trading_hub=NP15&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=AS_REQ&market_run_id=DAM&anc_type=ALL&anc_region=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=AS_RESULTS&market_run_id=DAM&anc_type=ALL&anc_region=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ATL_APNODE&APnode_type=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ATL_AS_REGION_MAP&as_region_id=A54_CNTR&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ATL_BAA_TIE&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=3
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ATL_CBNODE&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=2
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ATL_GEN_CAP_LST&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=4
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ATL_HUB&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ATL_ITC_SP&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=3
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ATL_LAP&APnode_type=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ATL_OSM&msg_severity=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ATL_PEAK_ON_OFF&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ATL_PNODE_MAP&pnode_id=KEARNY_7_KY2D&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ATL_PUB&market_run_id=DAM&oasis_section=ALL&status=ALL&atlpubversion=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ATL_PUB_SCHED&market_run_id=DAM&oasis_section=ALL&publication_type=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ATL_RUC_ZONE_MAP&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ATL_SP&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=3
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ATL_SP_TIE&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=3
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ATL_TAC_AREA_MAP&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ATL_TIEPOINT&resource_type=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ATL_TI&Ti_type=ALL&wecc_path=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=CB_NODAL_GRP_CNSTR_PRC&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=CMMT_RA_MLC&market_run_id=DAM&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=CMMT_RMR&market_run_id=DAM&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=CRR_CLEARING&market_name=ALL&market_term=ALL&time_of_use=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_AGGR_FLEX_RAMP&market_run_id=RTD&baa_grp_id=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=4
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_AGGR_FLEX_RAMP&market_run_id=RTPD&baa_grp_id=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=4
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_BAA_MKT_EVENTS&market_run_id=RTD&baa_grp_id=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=7
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_BASE_NSI&market_run_id=DAM&baa_id=ALL&snapshot_indicator=DA&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=2
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_BASE_NSI&market_run_id=RTD&baa_id=ALL&snapshot_indicator=T75MIN&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=2
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_BASE_NSI&market_run_id=RTPD&baa_id=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=2
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_CB_MKT_SUM&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_CD_SLRS&market_run_id=RTM&tac_zone_name=ALL&schedule=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_DISP&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_EA&energy_type=ALL&opr_interval=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_EA&energy_type=ALL&opr_interval=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=2
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_EIM_DYN_NSI&market_run_id=ALL&baa_id=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=2
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_EIM_DYN_NSI&market_run_id=RTD&baa_id=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=2
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_EIM_DYN_NSI&market_run_id=RTPD&baa_id=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=2
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_EIM_FLEX_RAMP_INPUT&market_run_id=RTM&baa_grp_id=ALL&snapshot_indicator=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=6
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_EIM_TRANSFER_LIMITS&market_run_id=ALL&baa_grp_id=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=2
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_EIM_TRANSFER_LIMITS&market_run_id=RTD&baa_grp_id=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=2
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_EIM_TRANSFER_LIMITS&market_run_id=RTPD&baa_grp_id=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=2
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_EIM_TRANSFER_LIMITS_TIE&market_run_id=RTD&baa_grp_id=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=5
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_EIM_TRANSFER_LIMITS_TIE&market_run_id=RTPD&baa_grp_id=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=5
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_EIM_TRANSFER&market_run_id=ALL&baa_grp_id=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=2
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_EIM_TRANSFER&market_run_id=RTD&baa_grp_id=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=2
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_EIM_TRANSFER&market_run_id=RTPD&baa_grp_id=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=2
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_EIM_TRANSFER_TIE&market_run_id=ALL&baa_grp_id=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=4
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_EIM_TRANSFER_TIE&market_run_id=RTD&baa_grp_id=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=4
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_EIM_TRANSFER_TIE&market_run_id=RTPD&baa_grp_id=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=4
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_FLEX_RAMP_DC&market_run_id=RTD&baa_grp_id=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=4
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_FLEX_RAMP_DC&market_run_id=RTPD&baa_grp_id=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=4
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_FLEX_RAMP_REQT&market_run_id=RTD&baa_grp_id=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=4
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_FLEX_RAMP_REQT&market_run_id=RTPD&baa_grp_id=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=4
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_FLEX_RAMP_REQT&market_run_id=RTPD&baa_grp_id=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=4
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_HRLY_BASE_LOSS&market_run_id=DAM&baa_id=ALL&snapshot_indicator=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=4
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_HRLY_BASE_LOSS&market_run_id=RTM&baa_id=ALL&snapshot_indicator=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=2
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_HRLY_BASE_NSI&market_run_id=DAM&baa_id=ALL&snapshot_indicator=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=4
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_HRLY_BASE_NSI&market_run_id=RTM&baa_id=ALL&snapshot_indicator=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=2
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_LOSS&market_run_id=DAM&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_MPM&market_run_id=DAM&baa_id=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=2
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_MPM&market_run_id=RTM&execution_type=HASP&baa_id=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=2
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_MPM&market_run_id=RTM&execution_type=HASP&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_MPM&market_run_id=RTM&execution_type=RTD&baa_id=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=2
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_MPM&market_run_id=RTM&execution_type=RTPD&baa_id=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=2
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_MPM&market_run_id=RTM&execution_type=RTPD&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_SLRS&market_run_id=DAM&tac_zone_name=ALL&schedule=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_UNCERTAINTY_MV&market_run_id=RTD&baa_grp_id=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=4
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=ENE_WIND_SOLAR_SUMMARY&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=5
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_AS&market_run_id=DAM&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1&anc_type=ALL&anc_region=ALL
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_CD_INTVL_LMP&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1&market_run_id=RTM&grp_type=ALL_APNODES
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_CD_RTM_FLOWGATE&market_run_id=RTM&ti_id=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_CD_RTM_NOMOGRAM&market_run_id=RTM&nomogram_id=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_CD_SPTIE_LMP&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=3&market_run_id=RTM&grp_type=ALL_APNODES
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_CNSTR&market_run_id=DAM&ti_id=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_CURR_HUB_LMP&startdatetime=_START_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_CURR_LMP&node=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_CURR_LMP&node=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=2
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_DAM_SCH_CNSTR&market_run_id=DAM&startdatetime=_START_T08:00-0000&enddatetime=_END_T08:00-0000&version=8
#http://oasis.caiso.com/oasisapi/SingleZip?&queryname=PRC_DAM_SCH_CNSTR&market_run_id=DAM&startdatetime=_START_T08:00-0000&enddatetime=_END_T08:00-0000&constraint_type=DC%20TRANSFER%20DEFINITION&version=8
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_DS_REF&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1&market_run_id=DAM&node_id=ALL
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_DS_REF&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1&market_run_id=DAM&node_id=LAPLMG1_7_B2
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_DS_REF&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=3&market_run_id=DAM&node_id=ALL
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_DS_REF&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=3&market_run_id=DAM&node_id=DGAP_PGE-APND
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_EIM_GHG&market_run_id=RTD&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=2
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_EIM_GHG&market_run_id=RTPD&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=2
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_FLEX_RAMP&market_run_id=DAM&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_FLEX_RAMP&market_run_id=RTD&baa_grp_id=PACE&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=2&grp_type=ALL
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_FLEX_RAMP&market_run_id=RTD&baa_grp_id=PACE&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=2&grp_type=CURR
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_FLEX_RAMP&market_run_id=RTD&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1&grp_type=ALL
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_FLEX_RAMP&market_run_id=RTD&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1&grp_type=CURR
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_FLEX_RAMP&market_run_id=RTPD&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1&grp_type=ALL
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_FLEX_RAMP&market_run_id=RTPD&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1&grp_type=CURR
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_FUEL&fuel_region_id=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_GHG_ALLOWANCE&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_HASP_LMP&startdatetime=_START_T07:00-0000&enddatetime=_END_T08:00-0000&version=1&market_run_id=HASP&grp_type=ALL_APNODES
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_HASP_LMP&startdatetime=_START_T07:00-0000&enddatetime=_END_T08:00-0000&version=2&market_run_id=HASP&grp_type=ALL_APNODES
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_HASP_LMP&startdatetime=_START_T07:00-0000&enddatetime=_END_T08:00-0000&version=3&market_run_id=HASP&grp_type=ALL_APNODES
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_INTVL_AS&market_run_id=RTM&startdatetime=_START_T07:00-0000&enddatetime=_END_T08:00-0000&version=1&anc_type=ALL&anc_region=ALL
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_INTVL_LMP&startdatetime=_START_T07:00-0000&enddatetime=_END_T08:00-0000&version=1&market_run_id=RTM&grp_type=ALL_APNODES
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_INTVL_LMP&startdatetime=_START_T07:00-0000&enddatetime=_END_T08:00-0000&version=2&market_run_id=RTM&grp_type=ALL_APNODE
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_INTVL_LMP&startdatetime=_START_T07:00-0000&enddatetime=_END_T08:00-0000&version=3&market_run_id=RTM&grp_type=ALL_APNODES
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_LMP&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1&market_run_id=DAM&grp_type=ALL_APNODES
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_MPM_CNSTR_CMP&market_run_id=DAM&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_MPM_CNSTR_CMP&market_run_id=HASP&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_MPM_CNSTR_CMP&market_run_id=RTD&startdatetime=_START_T08:00-0000&enddatetime=_END_T08:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_MPM_CNSTR_CMP&market_run_id=RTPD&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_MPM_CNSTR&market_run_id=DAM&ti_id=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_MPM_DEFAULT_CMP&market_run_id=DAM&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=5
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_MPM_DEFAULT_CMP&market_run_id=RTM&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=5
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_MPM_LMP&market_run_id=DAM&grp_type=ALL_APNODES&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_MPM_NOMOGRAM_CMP&market_run_id=DAM&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_MPM_NOMOGRAM&market_run_id=DAM&nomogram_id=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_MPM_REF_BUS&market_run_id=DAM&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_MPM_RTM_FLOWGATE&market_run_id=HASP&ti_id=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_MPM_RTM_FLOWGATE&market_run_id=RTPD&ti_id=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_MPM_RTM_LMP&market_run_id=HASP&grp_type=ALL_APNODES&startdatetime=_START_T06:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_MPM_RTM_LMP&market_run_id=HASP&grp_type=ALL_APNODES&startdatetime=_START_T06:00-0000&enddatetime=_END_T07:00-0000&version=2OR
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_MPM_RTM_LMP&market_run_id=RTPD&grp_type=ALL_APNODES&startdatetime=_START_T06:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_MPM_RTM_LMP&market_run_id=RTPD&grp_type=ALL_APNODES&startdatetime=_START_T06:00-0000&enddatetime=_END_T07:00-0000&version=2
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_MPM_RTM_NOMOGRAM_CMP&market_run_id=HASP&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_MPM_RTM_NOMOGRAM_CMP&market_run_id=RTD&startdatetime=_START_T08:00-0000&enddatetime=_END_T08:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_MPM_RTM_NOMOGRAM_CMP&market_run_id=RTPD&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_MPM_RTM_NOMOGRAM&market_run_id=HASP&nomogram_id=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_MPM_RTM_NOMOGRAM&market_run_id=RTPD&nomogram_id=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_MPM_RTM_REF_BUS&market_run_id=HASP&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_MPM_RTM_REF_BUS&market_run_id=RTD&startdatetime=_START_T08:00-0000&enddatetime=_END_T08:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_MPM_RTM_REF_BUS&market_run_id=RTPD&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_NOMOGRAM&market_run_id=DAM&nomogram_id=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_RTM_FLOWGATE&market_run_id=RTM&node=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_RTM_LAP&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=6&market_run_id=RTM&grp_type=ALL_APNODES
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_RTM_NOMOGRAM&market_run_id=RTM&nomogram_id=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_RTM_SCH_CNSTR&market_run_id=RTD&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=4
#http://oasis.caiso.com/oasisapi/SingleZip?&queryname=PRC_RTM_SCH_CNSTR&market_run_id=RTD&startdatetime=_START_T08:00-0000&enddatetime=_END_T08:00-0000&constraint_type=DC%20TRANSFER%20DEFINITION&version=4
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_RTM_SCH_CNSTR&market_run_id=RTPD&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=4
#http://oasis.caiso.com/oasisapi/SingleZip?&queryname=PRC_RTM_SCH_CNSTR&market_run_id=RTPD&startdatetime=_START_T08:00-0000&enddatetime=_END_T08:00-0000&constraint_type=DC%20TRANSFER%20DEFINITION&version=4
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_RTPD_LMP&startdatetime=_START_T07:00-0000&enddatetime=_END_T08:00-0000&version=1&market_run_id=RTPD&grp_type=ALL_APNODES
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_RTPD_LMP&startdatetime=_START_T07:00-0000&enddatetime=_END_T08:00-0000&version=2&market_run_id=RTPD&grp_type=ALL_APNODES
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_RTPD_LMP&startdatetime=_START_T07:00-0000&enddatetime=_END_T08:00-0000&version=3&market_run_id=RTPD&grp_type=ALL_APNODES
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_SPTIE_LMP&startdatetime=_START_T07:00-0000&enddatetime=_END_T08:00-0000&version=3&market_run_id=RTD&grp_type=ALL_APNODES
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_SPTIE_LMP&startdatetime=_START_T07:00-0000&enddatetime=_END_T08:00-0000&version=3&market_run_id=RTPD&grp_type=ALL_APNODES
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_SPTIE_LMP&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=3&market_run_id=DAM&grp_type=ALL_APNODES
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_SPTIE_LMP&startdatetime=_START_T07:00-0000&enddatetime=_END_T08:00-0000&version=4&market_run_id=RTD&grp_type=ALL_APNODES
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_SPTIE_LMP&startdatetime=_START_T07:00-0000&enddatetime=_END_T08:00-0000&version=4&market_run_id=RTPD&grp_type=ALL_APNODES
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_SPTIE_LMP&startdatetime=_START_T07:00-0000&enddatetime=_END_T08:00-0000&version=5&market_run_id=RTD&grp_type=ALL_APNODES
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_SPTIE_LMP&startdatetime=_START_T07:00-0000&enddatetime=_END_T08:00-0000&version=5&market_run_id=RTPD&grp_type=ALL_APNODES
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_SPTIE_LMP&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=4&market_run_id=DAM&grp_type=ALL_APNODES
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=PRC_SPTIE_LMP&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=5&market_run_id=DAM&grp_type=ALL_APNODES
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=SLD_ADV_FCST&market_run_id=RTD&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=4
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=SLD_ADV_FCST&market_run_id=RTPD&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=4
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=SLD_FCST&market_run_id=2DA&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1PRC_MPM_DEFAULT_CMP
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=SLD_FCST&market_run_id=7DA&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=SLD_FCST&market_run_id=ACTUAL&startdatetime=_START_T08:00-0000&enddatetime=_END_T08:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=SLD_FCST&market_run_id=DAM&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=SLD_FCST&market_run_id=RTM&execution_type=RTD&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=SLD_FCST&market_run_id=RTM&execution_type=RTPD&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=SLD_FCST_PEAK&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=SLD_REN_FCST&market_run_id=DAM&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=SLD_REN_FCST&market_run_id=RTD&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=SLD_REN_FCST&market_run_id=RTPD&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=SLD_SF_EVAL_DMD_FCST&granularity=15MIN&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=4
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=SLD_SF_EVAL_DMD_FCST&granularity=HOURLY&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=4
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=TRNS_ATC&market_run_id=DAM&ti_id=ALL&ti_direction=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=TRNS_ATC&market_run_id=RTPD&ti_id=ALL&ti_direction=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=TRNS_CURR_USAGE&ti_id=ALL&ti_direction=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=TRNS_CURR_USAGE&ti_id=ALL&ti_direction=ALL&tr_type=TRNS_AS_IMPORT_IFM&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=TRNS_OUTAGE&ti_id=ALL&ti_direction=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=TRNS_USAGE&market_run_id=DAM&ti_id=ALL&ti_direction=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=TRNS_USAGE&market_run_id=DAM&ti_id=ALL&ti_direction=ALL&tr_type=TRNS_AS_IMPORT_IFM&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
#http://oasis.caiso.com/oasisapi/SingleZip?queryname=TRNS_USAGE&market_run_id=RTPD&ti_id=ALL&ti_direction=ALL&startdatetime=_START_T07:00-0000&enddatetime=_END_T07:00-0000&version=1
